# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/kpsylock/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Users/kpsylock/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kpsylock/projects/lem-in

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kpsylock/projects/lem-in

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/kpsylock/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Users/kpsylock/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kpsylock/projects/lem-in/CMakeFiles /Users/kpsylock/projects/lem-in/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kpsylock/projects/lem-in/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lem-in

# Build rule for target.
lem-in: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lem-in
.PHONY : lem-in

# fast build rule for target.
lem-in/fast:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/build
.PHONY : lem-in/fast

#=============================================================================
# Target rules for targets named libft

# Build rule for target.
libft: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libft
.PHONY : libft

# fast build rule for target.
libft/fast:
	$(MAKE) -f libft/CMakeFiles/libft.dir/build.make libft/CMakeFiles/libft.dir/build
.PHONY : libft/fast

src/answer_ants_run.o: src/answer_ants_run.c.o

.PHONY : src/answer_ants_run.o

# target to build an object file
src/answer_ants_run.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/answer_ants_run.c.o
.PHONY : src/answer_ants_run.c.o

src/answer_ants_run.i: src/answer_ants_run.c.i

.PHONY : src/answer_ants_run.i

# target to preprocess a source file
src/answer_ants_run.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/answer_ants_run.c.i
.PHONY : src/answer_ants_run.c.i

src/answer_ants_run.s: src/answer_ants_run.c.s

.PHONY : src/answer_ants_run.s

# target to generate assembly for a file
src/answer_ants_run.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/answer_ants_run.c.s
.PHONY : src/answer_ants_run.c.s

src/bfs.o: src/bfs.c.o

.PHONY : src/bfs.o

# target to build an object file
src/bfs.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/bfs.c.o
.PHONY : src/bfs.c.o

src/bfs.i: src/bfs.c.i

.PHONY : src/bfs.i

# target to preprocess a source file
src/bfs.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/bfs.c.i
.PHONY : src/bfs.c.i

src/bfs.s: src/bfs.c.s

.PHONY : src/bfs.s

# target to generate assembly for a file
src/bfs.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/bfs.c.s
.PHONY : src/bfs.c.s

src/debug_info.o: src/debug_info.c.o

.PHONY : src/debug_info.o

# target to build an object file
src/debug_info.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/debug_info.c.o
.PHONY : src/debug_info.c.o

src/debug_info.i: src/debug_info.c.i

.PHONY : src/debug_info.i

# target to preprocess a source file
src/debug_info.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/debug_info.c.i
.PHONY : src/debug_info.c.i

src/debug_info.s: src/debug_info.c.s

.PHONY : src/debug_info.s

# target to generate assembly for a file
src/debug_info.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/debug_info.c.s
.PHONY : src/debug_info.c.s

src/destroyers.o: src/destroyers.c.o

.PHONY : src/destroyers.o

# target to build an object file
src/destroyers.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/destroyers.c.o
.PHONY : src/destroyers.c.o

src/destroyers.i: src/destroyers.c.i

.PHONY : src/destroyers.i

# target to preprocess a source file
src/destroyers.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/destroyers.c.i
.PHONY : src/destroyers.c.i

src/destroyers.s: src/destroyers.c.s

.PHONY : src/destroyers.s

# target to generate assembly for a file
src/destroyers.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/destroyers.c.s
.PHONY : src/destroyers.c.s

src/find_way.o: src/find_way.c.o

.PHONY : src/find_way.o

# target to build an object file
src/find_way.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/find_way.c.o
.PHONY : src/find_way.c.o

src/find_way.i: src/find_way.c.i

.PHONY : src/find_way.i

# target to preprocess a source file
src/find_way.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/find_way.c.i
.PHONY : src/find_way.c.i

src/find_way.s: src/find_way.c.s

.PHONY : src/find_way.s

# target to generate assembly for a file
src/find_way.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/find_way.c.s
.PHONY : src/find_way.c.s

src/get_ants.o: src/get_ants.c.o

.PHONY : src/get_ants.o

# target to build an object file
src/get_ants.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_ants.c.o
.PHONY : src/get_ants.c.o

src/get_ants.i: src/get_ants.c.i

.PHONY : src/get_ants.i

# target to preprocess a source file
src/get_ants.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_ants.c.i
.PHONY : src/get_ants.c.i

src/get_ants.s: src/get_ants.c.s

.PHONY : src/get_ants.s

# target to generate assembly for a file
src/get_ants.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_ants.c.s
.PHONY : src/get_ants.c.s

src/get_data.o: src/get_data.c.o

.PHONY : src/get_data.o

# target to build an object file
src/get_data.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_data.c.o
.PHONY : src/get_data.c.o

src/get_data.i: src/get_data.c.i

.PHONY : src/get_data.i

# target to preprocess a source file
src/get_data.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_data.c.i
.PHONY : src/get_data.c.i

src/get_data.s: src/get_data.c.s

.PHONY : src/get_data.s

# target to generate assembly for a file
src/get_data.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_data.c.s
.PHONY : src/get_data.c.s

src/get_links.o: src/get_links.c.o

.PHONY : src/get_links.o

# target to build an object file
src/get_links.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_links.c.o
.PHONY : src/get_links.c.o

src/get_links.i: src/get_links.c.i

.PHONY : src/get_links.i

# target to preprocess a source file
src/get_links.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_links.c.i
.PHONY : src/get_links.c.i

src/get_links.s: src/get_links.c.s

.PHONY : src/get_links.s

# target to generate assembly for a file
src/get_links.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_links.c.s
.PHONY : src/get_links.c.s

src/get_rooms.o: src/get_rooms.c.o

.PHONY : src/get_rooms.o

# target to build an object file
src/get_rooms.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_rooms.c.o
.PHONY : src/get_rooms.c.o

src/get_rooms.i: src/get_rooms.c.i

.PHONY : src/get_rooms.i

# target to preprocess a source file
src/get_rooms.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_rooms.c.i
.PHONY : src/get_rooms.c.i

src/get_rooms.s: src/get_rooms.c.s

.PHONY : src/get_rooms.s

# target to generate assembly for a file
src/get_rooms.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/get_rooms.c.s
.PHONY : src/get_rooms.c.s

src/init_data.o: src/init_data.c.o

.PHONY : src/init_data.o

# target to build an object file
src/init_data.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/init_data.c.o
.PHONY : src/init_data.c.o

src/init_data.i: src/init_data.c.i

.PHONY : src/init_data.i

# target to preprocess a source file
src/init_data.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/init_data.c.i
.PHONY : src/init_data.c.i

src/init_data.s: src/init_data.c.s

.PHONY : src/init_data.s

# target to generate assembly for a file
src/init_data.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/init_data.c.s
.PHONY : src/init_data.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/main.c.s
.PHONY : src/main.c.s

src/store_input_strings.o: src/store_input_strings.c.o

.PHONY : src/store_input_strings.o

# target to build an object file
src/store_input_strings.c.o:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/store_input_strings.c.o
.PHONY : src/store_input_strings.c.o

src/store_input_strings.i: src/store_input_strings.c.i

.PHONY : src/store_input_strings.i

# target to preprocess a source file
src/store_input_strings.c.i:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/store_input_strings.c.i
.PHONY : src/store_input_strings.c.i

src/store_input_strings.s: src/store_input_strings.c.s

.PHONY : src/store_input_strings.s

# target to generate assembly for a file
src/store_input_strings.c.s:
	$(MAKE) -f CMakeFiles/lem-in.dir/build.make CMakeFiles/lem-in.dir/src/store_input_strings.c.s
.PHONY : src/store_input_strings.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... lem-in"
	@echo "... libft"
	@echo "... src/answer_ants_run.o"
	@echo "... src/answer_ants_run.i"
	@echo "... src/answer_ants_run.s"
	@echo "... src/bfs.o"
	@echo "... src/bfs.i"
	@echo "... src/bfs.s"
	@echo "... src/debug_info.o"
	@echo "... src/debug_info.i"
	@echo "... src/debug_info.s"
	@echo "... src/destroyers.o"
	@echo "... src/destroyers.i"
	@echo "... src/destroyers.s"
	@echo "... src/find_way.o"
	@echo "... src/find_way.i"
	@echo "... src/find_way.s"
	@echo "... src/get_ants.o"
	@echo "... src/get_ants.i"
	@echo "... src/get_ants.s"
	@echo "... src/get_data.o"
	@echo "... src/get_data.i"
	@echo "... src/get_data.s"
	@echo "... src/get_links.o"
	@echo "... src/get_links.i"
	@echo "... src/get_links.s"
	@echo "... src/get_rooms.o"
	@echo "... src/get_rooms.i"
	@echo "... src/get_rooms.s"
	@echo "... src/init_data.o"
	@echo "... src/init_data.i"
	@echo "... src/init_data.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/store_input_strings.o"
	@echo "... src/store_input_strings.i"
	@echo "... src/store_input_strings.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

